# Generated by Django 4.0.4 on 2022-06-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evaluator',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('evname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(default=10)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('utype', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('dis', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=None)),
                ('quantity', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='adslot',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('evname', models.CharField(max_length=30)),
                ('date', models.DateField(max_length=30)),
                ('time', models.TimeField(max_length=30)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goapp.login')),
            ],
        ),
    ]
