# Generated by Django 4.0.4 on 2022-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0002_remove_evaluator_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cit', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('dis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('dis', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
            ],
        ),
    ]
