# Generated by Django 4.0.4 on 2022-06-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0003_city_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='dis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goapp.district'),
        ),
    ]
