# Generated by Django 4.0.4 on 2022-06-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0004_alter_city_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='res',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
