# Generated by Django 4.0.4 on 2022-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='advise',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
