# Generated by Django 4.0.4 on 2022-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0007_adslot_advise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='dis',
            field=models.IntegerField(),
        ),
    ]
