# Generated by Django 4.0.4 on 2022-06-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0008_alter_city_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
