# Generated by Django 4.0.4 on 2022-06-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0010_alter_evaluator_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='e_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.evaluator'),
        ),
    ]
