# Generated by Django 4.0.4 on 2022-06-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0011_adslot_e_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adslot',
            old_name='e_id',
            new_name='e',
        ),
    ]
