# Generated by Django 4.0.4 on 2022-06-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0012_rename_e_id_adslot_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.login'),
        ),
    ]
