# Generated by Django 4.0.4 on 2022-06-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0013_evaluator_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='district',
            field=models.IntegerField(),
        ),
    ]
