# Generated by Django 4.0.4 on 2022-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0015_alter_adslot_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
