# Generated by Django 4.0.4 on 2022-06-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0016_user_promote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
