# Generated by Django 4.0.4 on 2022-06-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0019_rename_cart_cart_cartid'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=30)),
                ('amount', models.FloatField()),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('ord_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.order')),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.product')),
            ],
        ),
    ]
