# Generated by Django 4.0.4 on 2022-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0021_alter_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
