# Generated by Django 4.0.4 on 2022-06-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0023_alter_cart_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tprice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uprice',
            field=models.FloatField(null=True),
        ),
    ]
