# Generated by Django 4.0.4 on 2022-06-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0024_alter_cart_quantity_alter_cart_tprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.district'),
        ),
    ]
