# Generated by Django 4.0.4 on 2022-06-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0025_alter_evaluator_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.district'),
        ),
        migrations.AlterField(
            model_name='city',
            name='dis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.district'),
        ),
    ]
