# Generated by Django 4.0.4 on 2022-06-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0026_alter_adslot_district_alter_city_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='login',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.user'),
        ),
    ]
