# Generated by Django 4.0.4 on 2022-06-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0027_remove_order_login_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
