# Generated by Django 4.0.4 on 2022-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0028_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='ord_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
