# Generated by Django 4.0.4 on 2022-07-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0029_alter_order_order_id_alter_orderdetails_ord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transid',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.CreateModel(
            name='tbl_bank',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('card', models.CharField(max_length=16)),
                ('cvv', models.IntegerField()),
                ('expry', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.user')),
            ],
        ),
    ]
