# Generated by Django 4.0.4 on 2022-07-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0030_order_transid_tbl_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goapp.tbl_bank'),
        ),
    ]
