# Generated by Django 4.0.4 on 2022-07-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0031_order_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bid',
            new_name='b',
        ),
    ]
