# Generated by Django 4.0.4 on 2022-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0032_rename_bid_order_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_bank',
            old_name='bid',
            new_name='b_id',
        ),
    ]
