# Generated by Django 4.0.4 on 2022-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0036_alter_tbl_bank_expry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='ordered', max_length=30),
        ),
    ]
