# Generated by Django 4.0.4 on 2022-07-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0037_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(default='ordered', max_length=30),
        ),
    ]
