# Generated by Django 4.0.4 on 2022-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0040_culti_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='track',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
