# Generated by Django 4.0.4 on 2022-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0041_orderdetails_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='track',
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
